### ISSUE TITLE
About depth bins

### ISSUE THREAD

**Issue by hyBlue** [nianticlabs/manydepth#6]
Hi, 
Thanks for the interesting paper. It is really impressive and inspiring.
I want to ask you some questions about the binning strategy. 
In options.py, there are two options, inverse, and linear, but the linear is default and chosen for your model. 
As far as I know, many papers of MVS depth using DNN construct cost volume with planes sampled from the inverse depth space. But in your case,  does linear perform better than inverse sampling? Also, would you please explain any insights behind this choice?

**Comment by JamieWatson683** [comment]
Hi, thanks for your interest!

It's a good question - in our experiments we found that `inverse` performs slightly worse than `linear`, although not by much. This could be due to the depth ranges for the KITTI dataset - there are few very close pixels in the ground truth, and the range is from ~0.5m to ~100m+ (although evaluation is capped at 80m in general). 

Feel free to experiment with this and let me know if you find a better setting!

Thanks a lot

**Comment by hyBlue** [comment]
@JamieWatson683 
Great! Thank you for the explanation.
